CREATE TABLE [dbo].[PARTICIPANTE]
(
[IDPAR] [int] NOT NULL IDENTITY(1, 1),
[FECREGPAR] [datetime] NULL CONSTRAINT [DF__PARTICIPA__FECRE__24927208] DEFAULT (getdate()),
[NOMPAR] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APEPAR] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNIPAR] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPPAR] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CELPAR] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAPAR] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRPAR] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTPAR] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PARTICIPA__ESTPA__25869641] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PARTICIPANTE] ADD CONSTRAINT [IDPAR_PK] PRIMARY KEY CLUSTERED ([IDPAR]) ON [PRIMARY]
GO
