CREATE TABLE [dbo].[PONENTE]
(
[CODPON] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOMPON] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APEPON] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CELPON] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNIPON] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAPON] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRPON] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PONENTE] ADD CONSTRAINT [CODPON_PK] PRIMARY KEY CLUSTERED ([CODPON]) ON [PRIMARY]
GO
